/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/FcSCewU1ZsJ
 */
import Link from "next/link"
import { Switch } from "@/components/ui/switch"
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"

export function BaseLayout() {
  return (
    <div className="flex flex-col min-h-screen ">
      <header className="sticky top-0 z-10 bg-black text-white dark:bg-gray-800">
        <nav className="container mx-auto flex items-center justify-between py-4 px-6">
          <div className="flex items-center space-x-4">
            <MenuIcon className="h-6 w-6" />
            <Link className="block" href="#">
              PRICING
            </Link>
            <Link className="block" href="#">
              GAMES
            </Link>
            <Link className="block" href="#">
              LEARN
            </Link>
            <Link className="block" href="#">
              ORPHAN DICE
            </Link>
            <Link className="block" href="#">
              EVENTS
            </Link>
            <Link className="block" href="#">
              CONTACT
            </Link>
          </div>
          <div className="flex items-center space-x-4">
            <SearchIcon className="h-6 w-6" />
            <ShoppingCartIcon className="h-6 w-6" />
            <UserIcon className="h-6 w-6" />
            <Switch checked={undefined} className="ml-4" id="dark-mode" onChange={undefined} />
          </div>
        </nav>
      </header>
      <section className="bg-[#1a1a1a] text-white dark:bg-gray-800">
        <div className="container mx-auto px-6 py-16 text-center">
          <h1 className="text-6xl font-bold mb-4">Embark on the Experimental</h1>
          <p className="mb-8">
            The Dice Wizard is always looking for new adventures to join. Here are some of the upcoming adventures, and
            some of the adventures that are waiting for you to join them.
          </p>
          <div className="flex justify-center space-x-4">
            <Button className="bg-white text-black dark:bg-gray-800 dark:text-white">GAMES</Button>
            <Button className="border-white text-white dark:border-gray-200 dark:text-gray-200" variant="outline">
              WORKSHOP
            </Button>
          </div>
        </div>
      </section>
      <section className="container mx-auto px-6 py-16">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <Card className="bg-black text-white dark:bg-gray-800 dark:text-gray-200">
            <CardContent>
              <img
                alt="Online Adventures"
                className="rounded-t-md"
                height="200"
                src="/icons/checkmark.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <h2 className="text-xl font-bold mt-4">Online Adventures (Escape from Reality)</h2>
              <p className="text-sm">GAMES</p>
            </CardContent>
          </Card>
          <Card className="bg-black text-white dark:bg-gray-800 dark:text-gray-200">
            <CardContent>
              <img
                alt="Model Painting Workshop"
                className="rounded-t-md"
                height="200"
                src="/icons/checkmark.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <h2 className="text-xl font-bold mt-4">Model Painting Workshop</h2>
              <p className="text-sm">WORKSHOP</p>
            </CardContent>
          </Card>
          <Card className="bg-black text-white dark:bg-gray-800 dark:text-gray-200">
            <CardContent>
              <img
                alt="Beginner Games"
                className="rounded-t-md"
                height="200"
                src="/icons/checkmark.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <h2 className="text-xl font-bold mt-4">Beginner Games</h2>
              <p className="text-sm">GAMES</p>
            </CardContent>
          </Card>
        </div>
      </section>
      <section className="bg-[#1a1a1a] text-white py-16 dark:bg-gray-800">
        <div className="container mx-auto px-6 text-center">
          <h2 className="text-3xl font-bold mb-4">Ready to start your adventure?</h2>
          <Button className="bg-white text-black dark:bg-gray-800 dark:text-white">Join Now</Button>
        </div>
      </section>
      <footer className="bg-black text-white py-4 dark:bg-gray-800">
        <div className="container mx-auto px-6 text-center">
          <p>© 2024 Dice Adventures. All rights reserved.</p>
        </div>
      </footer>
    </div>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function ShoppingCartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
