/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/gr6TRl3AThK
 */
import Link from "next/link"

/**
 * Renders the hero header section with a background image, title, and description.
 *
 * @return {JSX.Element} The hero header section JSX element
 */
export function HeroHeader() {
  return (
    <section className="w-full">
      <div className="relative">
        <div className="absolute inset-0">
          <img
            alt="Hero"
            className="object-cover w-full h-full"
            height="800"
            src="./src/assets/wizard.png"
            style={{ aspectRatio: "2600/800", objectFit: "cover" }}
            width="2600"
          />
          <div className="absolute inset-0 bg-gray-900/50" />
        </div>
        <div className="relative flex items-center justify-center w-full min-h-screen py-12 layout-hero md:py-24 lg:py-32 xl:py-40">
          <div className="container flex flex-1 flex-col items-center justify-center space-y-4 px-6">
            <div className="flex flex-col items-center space-y-2 text-center">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl text-gray-100 font-NodestoCapsCondensed">
                Choose Your Adventure
              </h1>

              <p className="max-w-[600px] text-gray-300 md:text-xl dark:text-gray-400">
                Unleash Your Inner Hero
              </p>
              <p className="max-w-[600px] text-gray-300 md:text-xl dark:text-gray-400">
                Join a DiceWizard Game Today!
              </p>
            </div>
<Link
  href="#" // Replace with your desired link
  className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
>
  Sign up
</Link>
          </div>
        </div>
      </div>
    </section>
  )
}

