/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lOnLDkHkH5k
 */
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function PriceComparisonTable() {
  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead className="w-[200px]">User Segments</TableHead>
          <TableHead className="w-[200px]">Beginners</TableHead>
          <TableHead className="w-[200px]">Adventurers</TableHead>
          <TableHead className="w-[200px]">Heroes</TableHead>
          <TableHead className="w-[200px]">Online</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        <TableRow>
          <TableCell className="font-medium">Duration</TableCell>
          <TableCell>3-hour sessions</TableCell>
          <TableCell>3-hour sessions</TableCell>
          <TableCell>3-hour sessions</TableCell>
          <TableCell>3-hour sessions</TableCell>
        </TableRow>
        <TableRow>
          <TableCell className="font-medium">Consent</TableCell>
          <TableCell>
            <ul className="m-0 pl-4 list-disc">
              <li>Mandatory forms</li>
              <li>In-game tools</li>
              <li>Comment box for concerns</li>
            </ul>
          </TableCell>
          <TableCell>
            <ul className="m-0 pl-4 list-disc">
              <li>Mandatory forms</li>
              <li>In-game tools</li>
              <li>Comment box for concerns</li>
            </ul>
          </TableCell>
          <TableCell>
            <ul className="m-0 pl-4 list-disc">
              <li>Mandatory forms</li>
              <li>In-game tools</li>
              <li>Comment box for concerns</li>
            </ul>
          </TableCell>
          <TableCell>
            <ul className="m-0 pl-4 list-disc">
              <li>Mandatory forms</li>
              <li>In-game tools</li>
              <li>Comment box for concerns</li>
            </ul>
          </TableCell>
        </TableRow>
        <TableRow>
          <TableCell className="font-medium">Safety</TableCell>
          <TableCell>
            <ul className="m-0 pl-4 list-disc">
              <li>Stickers</li>
              <li>Pins</li>
              <li>Customization options</li>
            </ul>
          </TableCell>
          <TableCell>
            <ul className="m-0 pl-4 list-disc">
              <li>Stickers</li>
              <li>Pins</li>
              <li>Customization options</li>
            </ul>
          </TableCell>
          <TableCell>
            <ul className="m-0 pl-4 list-disc">
              <li>Stickers</li>
              <li>Pins</li>
              <li>Customization options</li>
            </ul>
          </TableCell>
          <TableCell>
            <ul className="m-0 pl-4 list-disc">
              <li>Stickers</li>
              <li>Pins</li>
              <li>Customization options</li>
            </ul>
          </TableCell>
        </TableRow>
        <TableRow>
          <TableCell className="font-medium">Rewards</TableCell>
          <TableCell>
            <ul className="m-0 pl-4 list-disc">
              <li>Max 5 players per game</li>
            </ul>
          </TableCell>
          <TableCell>
            <ul className="m-0 pl-4 list-disc">
              <li>Max 5 players per game</li>
            </ul>
          </TableCell>
          <TableCell>
            <ul className="m-0 pl-4 list-disc">
              <li>Max 5 players per game</li>
            </ul>
          </TableCell>
          <TableCell>
            <ul className="m-0 pl-4 list-disc">
              <li>Max 5 players per game</li>
            </ul>
          </TableCell>
        </TableRow>
        <TableRow>
          <TableCell className="font-medium">Capacity</TableCell>
          <TableCell>Based on age: Juniors 8-12, Teens 13-17, Adults 18+</TableCell>
          <TableCell>Based on age: Juniors 8-12, Teens 13-17, Adults 18+</TableCell>
          <TableCell>Based on age: Juniors 8-12, Teens 13-17, Adults 18+</TableCell>
          <TableCell>Based on age: Juniors 8-12, Teens 13-17, Adults 18+</TableCell>
        </TableRow>
        <TableRow>
          <TableCell className="font-medium">Matching</TableCell>
          <TableCell className="text-center">
            <CheckCircleIcon className="h-4 w-4 m-auto" />
          </TableCell>
          <TableCell className="text-center">
            <CheckCircleIcon className="h-4 w-4 m-auto" />
          </TableCell>
          <TableCell className="text-center">
            <CheckCircleIcon className="h-4 w-4 m-auto" />
          </TableCell>
          <TableCell className="text-center">
            <CheckCircleIcon className="h-4 w-4 m-auto" />
          </TableCell>
        </TableRow>
        <TableRow>
          <TableCell className="font-medium">Documentation</TableCell>
          <TableCell>
            <ul className="m-0 pl-4 list-disc">
              <li>3D models</li>
              <li>Immortalized campaigns</li>
            </ul>
          </TableCell>
          <TableCell>
            <ul className="m-0 pl-4 list-disc">
              <li>3D models</li>
              <li>Immortalized campaigns</li>
            </ul>
          </TableCell>
          <TableCell>
            <ul className="m-0 pl-4 list-disc">
              <li>3D models</li>
              <li>Immortalized campaigns</li>
            </ul>
          </TableCell>
          <TableCell>
            <ul className="m-0 pl-4 list-disc">
              <li>3D models</li>
              <li>Immortalized campaigns</li>
            </ul>
          </TableCell>
        </TableRow>
        <TableRow>
          <TableCell>Handouts</TableCell>
          <TableCell>Character sheets, Maps</TableCell>
          <TableCell>Character sheets, Maps</TableCell>
          <TableCell>Character sheets, Maps</TableCell>
          <TableCell>Character sheets, Maps</TableCell>
        </TableRow>
      </TableBody>
    </Table>
  )
}


function CheckCircleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
      <polyline points="22 4 12 14.01 9 11.01" />
    </svg>
  )
}
