/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/HZuPiYcQvGl
 */
import { NavigationMenuLink, NavigationMenuItem, NavigationMenuList, NavigationMenu } from "@/components/ui/navigation-menu"
import { Switch } from "@/components/ui/switch"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function WizardMenu() {
  return (
    <nav className="bg-[#0d0d2b] bg-opacity-80">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          <div className="flex items-center justify-center w-full"> {/* Modified this line */}
            <div className="flex-shrink-0">
              <h1 className="text-white text-xl font-bold text-3d animate-pulse">DICE WIZARD</h1>
            </div>
            <div className="hidden md:flex w-full justify-center"> {/* Modified this line */}
              <NavigationMenu>
                 <NavigationMenuList className="flex items-baseline space-x-4">
                  <NavigationMenuItem>
                    <NavigationMenuLink
                      className="hover:bg-gray-700 rounded-md px-2 py-1 transition-colors duration-200"
                      href="#"
                    >
                      Games
                    </NavigationMenuLink>
                  </NavigationMenuItem>
                  <NavigationMenuItem>
                    <NavigationMenuLink
                      className="hover:bg-gray-700 rounded-md px-2 py-1 transition-colors duration-200"
                      href="#"
                    >
                      Register
                    </NavigationMenuLink>
                  </NavigationMenuItem>
                  <NavigationMenuItem>
                    <NavigationMenuLink
                      className="hover:bg-gray-700 rounded-md px-2 py-1 transition-colors duration-200"
                      href="#"
                    >
                      Learn
                    </NavigationMenuLink>
                  </NavigationMenuItem>
                  <NavigationMenuItem>
                    <NavigationMenuLink
                      className="hover:bg-gray-700 rounded-md px-2 py-1 transition-colors duration-200"
                      href="#"
                    >
                      Loot
                    </NavigationMenuLink>
                  </NavigationMenuItem>
                  <NavigationMenuItem>
                    <NavigationMenuLink
                      className="hover:bg-gray-700 rounded-md px-2 py-1 transition-colors duration-200"
                      href="#"
                    >
                      Events
                    </NavigationMenuLink>
                  </NavigationMenuItem>
                  <NavigationMenuItem>
                    <NavigationMenuLink
                      className="hover:bg-gray-700 rounded-md px-2 py-1 transition-colors duration-200"
                      href="#"
                    >
                      Join
                    </NavigationMenuLink>
                  </NavigationMenuItem>
                  <NavigationMenuItem>
                    <NavigationMenuLink
                      className="hover:bg-gray-700 rounded-md px-2 py-1 transition-colors duration-200"
                      href="#"
                    >
                      Contact
                    </NavigationMenuLink>
                  </NavigationMenuItem>
                </NavigationMenuList>
              </NavigationMenu>
            </div>
          </div>
          <div className="hidden md:block">
            <div className="ml-4 flex items-center md:ml-6">
              <Switch className="ml-auto" id="dark-mode" />
              <Label className="ml-2 text-white text-opacity-70" htmlFor="dark-mode">
                Dark Mode
              </Label>
            </div>
          </div>
          <div className="-mr-2 flex md:hidden">
            <Button className="inline-flex items-center justify-center p-2 rounded-md text-white text-opacity-70 hover:text-opacity-100 hover:bg-[#1a1a40] focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white transition-opacity duration-150 ease-in-out">
              <MenuIcon className="" />
            </Button>
          </div>
        </div>
      </div>
      <div className="md:hidden">
        <div className="px-2 pt-2 pb-3 space-y-1 sm:px-3">
          <Link
            className="text-white text-opacity-70 hover:text-opacity-100 block px-3 py-2 rounded-md text-base font-medium transition-opacity duration-150 ease-in-out"
            href="#"
          >
            Games
          </Link>
          <Link
            className="text-white text-opacity-70 hover:text-opacity-100 block px-3 py-2 rounded-md text-base font-medium transition-opacity duration-150 ease-in-out"
            href="#"
          >
            Register
          </Link>
          <Link
            className="text-white text-opacity-70 hover:text-opacity-100 block px-3 py-2 rounded-md text-base font-medium transition-opacity duration-150 ease-in-out"
            href="#"
          >
            Learn
          </Link>
          <Link
            className="text-white text-opacity-70 hover:text-opacity-100 block px-3 py-2 rounded-md text-base font-medium transition-opacity duration-150 ease-in-out"
            href="#"
          >
            Loot
          </Link>
          <Link
            className="text-white text-opacity-70 hover:text-opacity-100 block px-3 py-2 rounded-md text-base font-medium transition-opacity duration-150 ease-in-out"
            href="#"
          >
            Events
          </Link>
          <Link
            className="text-white text-opacity-70 hover:text-opacity-100 block px-3 py-2 rounded-md text-base font-medium transition-opacity duration-150 ease-in-out"
            href="#"
          >
            Join
          </Link>
          <Link
            className="text-white text-opacity-70 hover:text-opacity-100 block px-3 py-2 rounded-md text-base font-medium transition-opacity duration-150 ease-in-out"
            href="#"
          >
            Contact
          </Link>
        </div>
      </div>
    </nav>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}
